// src/app/layout.tsx
import './globals.css';
import { Inter } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import Navbar from '@/components/Navbar'; // Import the Navbar

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Full Stack AI Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar /> {/* Add Navbar here */}
          <main>{children}</main> {/* Wrap children in a main tag if desired */}
        </SessionProvider>
      </body>
    </html>
  );
}