// src/app/layout.tsx
import './globals.css';
import { Inter } from 'next/font/google';
import { SessionProvider } from 'next-auth/react'; // Import SessionProvider

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Full Stack AI Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap your children with SessionProvider */}
        <SessionProvider>
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}